### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by junxnone** [junxnone/autosidebartest#8]
[Supported Features](/Supported_Features)

## TODO

- [ ]  知识图谱 [[3d-force-graph](https://github.com/vasturiano/3d-force-graph)]
- [ ] 生成 `按修改日期` 排序页面
- [ ] 生成 `按创建日期` 排序页面
- [ ] 自动生成索引 ? 手动更定制化
- [ ] 文档存储位置 ? 分散存储更改标题时会更改位置
- [ ] 易用性问题, [`use this template` --> `最小修改`]
- [ ] mindmap
  - [x] markmap
- [x] `nohead` label 不创建文件头
- [x] Labels
- [x] Edit Button link 问题
- [x] prev/next page
- [x] NavBar
- [x] [mermaid](https://github.com/Leward/mermaid-docsify)
- [x] markdown content
- [x] katex plugin for latex math support
- [x] [Gitalk](https://github.com/gitalk/gitalk/blob/master/readme-cn.md)
- [x] 增加 edit 链接
- [x] Search Bar
- [x] 代码复制按钮
- [x] TOC
- [x] 字数&阅读用时统计
- [x] dark mode button
- [x] sidebar 折叠
- [x] wikilink
